# 발표에 쓰이는 테이블만 만들기

In [20]:
import pandas as pd
import numpy as np
from Fin import *
from Stat import *
import warnings
warnings.filterwarnings(action='ignore')
df = pd.read_excel("Data/kosdaq/Alldata.xlsx")
df_main_vars = df[['RNOA', 'deltaSGA', 'deltasale', 'deltaATO', 'GNOA', 'deltaACC', 'valPEIS','consen_cut']]

In [21]:
df['CompuConsen'].value_counts()

0    9091
3     748
4     742
2     370
1      19
Name: CompuConsen, dtype: int64

In [39]:
df[df['CompuConsen'] - df['consen_cut'] != 0 ][['Targetprice','Endprice', 'consen_cut', 'CompuConsen']]

       Targetprice  Endprice  consen_cut  CompuConsen
11         23000.0     10400           3            4
13          7500.0      6270           3            2
27         38250.0     32050           3            2
29         35000.0     22900           3            4
31         11000.0      7770           3            4
...            ...       ...         ...          ...
10525       5000.0      4375           3            2
10579       5750.0      4785           2            3
10599       8500.0      5370           3            4
10669      20700.0     13900           3            4
10685       9500.0      6070           3            4

[1103 rows x 4 columns]

# Table5_recoommand 별 통계

In [8]:
alldata, groupPEISdata = showTable5(df_main_vars)

Alldata count :  10970
consen : 0 count : 9072
consen : 1 count : 5
consen : 2 count : 115
consen : 3 count : 1759
consen : 4 count : 17

In [9]:
round(alldata,3).to_excel('Data/kosdaq/table5_1.xlsx')

In [10]:
round(groupPEISdata,3).to_excel('Data/kosdaq/table5_2.xlsx')

In [11]:
alldata

,Mean,Std,P20,Median,P80,Min,Max
RNOA,-0.093908,28.490082,-0.199363,0.047030,0.288477,-2677.181782,796.743691
deltaSGA,0.224255,37.305441,-0.025250,0.002257,0.038417,-1179.708727,3482.581120
deltasale,0.204124,3.539049,-0.121544,0.058390,0.278893,-7.761032,333.639940
deltaATO,-0.057112,1.183166,-0.224482,-0.025228,0.131860,-67.459073,68.085104
GNOA,-0.186365,48.056118,-0.368208,0.011300,0.442559,-4523.191252,1152.962748
deltaACC,-0.322250,20.899924,-0.192228,-0.015477,0.184604,-1785.503894,499.337866
valPEIS,0.000365,1.565304,-1.000000,0.000000,1.000000,-6.000000,6.000000

In [12]:
groupPEISdata

                 Mean         Std       P20    Median       P80          Min  \
0 RNOA      -0.176082   31.179279 -0.182847  0.037349  0.235819 -2677.181782
  deltaSGA   0.266041   41.019298 -0.025977  0.002659  0.041770 -1179.708727
  deltasale  0.198067    3.883029 -0.138157  0.043242  0.254503    -7.761032
  deltaATO  -0.052682    1.140592 -0.225216 -0.028395  0.126210   -67.459073
  GNOA       0.158998   21.899637 -0.353733  0.008592  0.420354 -1189.227340
  deltaACC  -0.257856   20.587249 -0.188550 -0.016268  0.172430 -1785.503894
  PEIS       0.023917    1.546666 -1.000000  0.000000  1.000000    -6.000000
1 RNOA       1.093714    1.539974  0.598357  1.238791  1.627732    -1.203738
  deltaSGA  -0.036366    0.101416 -0.051677 -0.006461  0.011445    -0.213134
  deltasale  0.263076    0.230237  0.101650  0.160331  0.465358     0.025739
  deltaATO   0.138306    0.358700 -0.014006  0.183942  0.404519    -0.443456
  GNOA       0.030487    1.985650 -0.762495 -0.258614  1.113560    -2.769700
  deltaACC  -0.375174    1.387290 -1.054743 -0.132147  0.234562    -2.403334
  PEIS      -0.200000    1.303840 -1.200000  0.000000  1.000000    -2.000000
2 RNOA       0.116143    0.605794 -0.171449  0.069794  0.491362    -2.596642
  deltaSGA   0.021358    0.064498 -0.010035  0.013196  0.051507    -0.179428
  deltasale -0.011462    0.293468 -0.183277 -0.028157  0.162112    -0.783239
  deltaATO  -0.213061    0.525815 -0.374831 -0.104423  0.012778    -2.500321
  GNOA       5.772512   52.473638 -0.312531  0.028377  0.563864    -5.291875
  deltaACC   0.083149    0.904995 -0.182672 -0.012720  0.259780    -3.885916
  PEIS      -0.695652    1.278527 -2.000000 -1.000000  0.000000    -4.000000
3 RNOA       0.305139    6.865307 -0.414675  0.143154  0.634605   -67.868961
  deltaSGA   0.024895    0.764904 -0.024434 -0.000597  0.025709    -5.606033
  deltasale  0.247538    0.563244 -0.001777  0.150071  0.404732    -0.968358
  deltaATO  -0.072261    1.410701 -0.212338 -0.003884  0.176645   -52.704211
  GNOA      -2.359313  108.358517 -0.470667  0.029132  0.528318 -4523.191252
  deltaACC  -0.681196   23.190434 -0.216622 -0.011045  0.244379  -959.135950
  PEIS      -0.069886    1.659881 -1.000000  0.000000  1.000000    -5.000000
4 RNOA       0.697725    2.776203 -0.517330  0.220293  1.071480    -4.331526
  deltaSGA   0.011502    0.115651 -0.013871  0.002256  0.017022    -0.240962
  deltasale  0.383238    1.139930  0.000751  0.048004  0.350940    -0.236636
  deltaATO   0.144372    1.007519 -0.188091 -0.039537  0.062588    -0.547158
  GNOA       0.081556    1.061675 -0.827702  0.047099  0.746706    -1.341214
  deltaACC  -0.272406    1.237625 -0.149842 -0.003985  0.382794    -4.498924
  PEIS      -0.529412    1.940285 -2.000000  0.000000  0.000000    -3.000000

                     Max
0 RNOA        796.743691
  deltaSGA   3482.581120
  deltasale   333.639940
  deltaATO     68.085104
  GNOA       1152.962748
  deltaACC    499.337866
  PEIS          6.000000
1 RNOA          3.133295
  deltaSGA      0.046363
  deltasale     0.569312
  deltaATO      0.469387
  GNOA          2.732656
  deltaACC      1.445339
  PEIS          1.000000
2 RNOA          1.892639
  deltaSGA      0.416334
  deltasale     1.557969
  deltaATO      0.667447
  GNOA        558.223685
  deltaACC      5.743146
  PEIS          2.000000
3 RNOA        178.490158
  deltaSGA     28.069164
  deltasale    10.650412
  deltaATO      2.626530
  GNOA        259.665862
  deltaACC     38.395841
  PEIS          6.000000
4 RNOA          9.544994
  deltaSGA      0.391699
  deltasale     4.739826
  deltaATO      3.986823
  GNOA          3.181901
  deltaACC      0.842273
  PEIS          4.000000

#

#

#

#

#

# Table6

In [13]:
Alldata = pd.read_excel("Data/kosdaq/Alldata.xlsx")
UseOnlyPort = Alldata[['회계년','Name','시가총액','consen_cut','CompuConsen','valPEIS','deltaprice','deltaearn']]

# 컨센별ALL & 컨센안에서 PEIS별

In [14]:
ConsenPorts = MakePortbyCriteria(UseOnlyPort, 'consen_cut')
for i in ConsenPorts:
    i.ConsenPEIS()

In [15]:
AllDatabyConsen = MakeTable6form(ConsenPorts)

In [16]:
table = []
for df in ConsenPorts:
    table.append(MakeTable6form(df.PEIS))
PEISConsentable = pd.concat(table)

In [17]:
Table6 = pd.concat([AllDatabyConsen, PEISConsentable])
Table6.index = [ ['All']*5+['No consen']*5+['Sell']*5+['Hold']*5+['Buy']*5+['S_Buy']*5, [5,4,3,2,1]*6   ]

In [18]:
Table6.to_excel('Data/kosdaq/table6.xlsx')
Table6.fillna(0)

             Earning increases  Earning decrease  Percentage of increse
All       5             4475.0            4598.0                   0.49
          4                2.0               3.0                   0.40
          3               48.0              67.0                   0.42
          2              906.0             854.0                   0.51
          1                6.0              11.0                   0.35
No consen 5              661.0             677.0                   0.49
          4              951.0            1005.0                   0.49
          3                0.0               0.0                   0.00
          2             1241.0            1297.0                   0.49
          1             1622.0            1619.0                   0.50
Sell      5                0.0               1.0                   0.00
          4                0.0               1.0                   0.00
          3                1.0               0.0                   1.00
          2                0.0               0.0                   0.00
          1                1.0               1.0                   0.50
Hold      5                5.0               6.0                   0.45
          4                6.0               7.0                   0.46
          3               15.0              22.0                   0.41
          2                0.0               0.0                   0.00
          1               22.0              32.0                   0.41
Buy       5              157.0             167.0                   0.48
          4              180.0             175.0                   0.51
          3                0.0               0.0                   0.00
          2              261.0             199.0                   0.57
          1              308.0             313.0                   0.50
S_Buy     5                1.0               1.0                   0.50
          4                1.0               4.0                   0.20
          3                1.0               0.0                   1.00
          2                0.0               0.0                   0.00
          1                3.0               6.0                   0.33

#

#

#







#

# Table 1

In [19]:
# 데이터 준비시키기
Table1_Series = UseOnlyPort.groupby(['회계년', 'consen_cut']).count()['Name']
Table1 = Table1_Series.unstack(1)

# 컬럼합 보여주기
colsum = Table1.sum().tolist()
newrow = len(Table1)
Table1.loc[newrow] = colsum
newrow = len(Table1)
Table1.loc[newrow] = Table = round(Table1.loc[newrow-1]/Table1.loc[newrow-1].sum(),2).tolist()
Table1.index = [ i for i in range(2010,2020)] + ['Total'] + ['Percentage']

# 로우합보여주기
rowsum = Table1.sum(axis=1)
Table1 = pd.concat([Table1, rowsum], axis = 1)
Table1.columns = ['No consen', 'Sell', 'Hold', 'Buy', 'S_Buy','Total']
# 마지막으로 보여주기
Table1.fillna(0,inplace = True)
Table1.to_excel('Data/kosdaq/table1.xlsx')
Table1

            No consen  Sell    Hold      Buy  S_Buy    Total
2010           807.00   0.0    7.00   136.00    2.0    952.0
2011           807.00   1.0    9.00   142.00    2.0    961.0
2012           812.00   0.0   10.00   139.00    0.0    961.0
2013           810.00   0.0   11.00   160.00    3.0    984.0
2014           845.00   1.0   11.00   180.00    2.0   1039.0
2015           905.00   1.0    8.00   198.00    1.0   1113.0
2016           956.00   1.0   18.00   200.00    3.0   1178.0
2017           993.00   1.0   15.00   214.00    1.0   1224.0
2018          1045.00   0.0   10.00   200.00    3.0   1258.0
2019          1093.00   0.0   16.00   191.00    0.0   1300.0
Total         9073.00   5.0  115.00  1760.00   17.0  10970.0
Percentage       0.83   0.0    0.01     0.16    0.0      1.0